name: build-api-systeminfo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.0
      - run: |
          python --version
          pip --version
