name: vars-and-secrets-usage

on: push

jobs:
  vars-and-secrets:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ttl.sh
      snowflake_database: dwh_stg
    steps:
      - name: Print context
        run: |
          env
