name: vars-and-secrets-usage

on: push

jobs:
  vars-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Default shell
        run: |
          env
      - name: Bash
        shell: bash
        run: |
          env
